### ISSUE TITLE
Tracing log does not work in hot loaded widgets

### ISSUE THREAD

**Issue by SamRodri** [SamRodri/zng#215]
#### I tried this code:

The `hot_reload` example.

#### Following these steps:

1 - Run hot_reload.
2- Cause a reload.

#### I saw this happen:

The `tracing::info!` on init and deinit only print for the first (static) version of the hot_node.

#### I expected this to happen:

Should print for the reloaded dynamic version too, because we pass the `tracing` dispatcher to the dylib.

#### Comments

The dispatcher sharing code is in [here](https://github.com/zng-ui/zng/blob/b0f660782181d0ac4b254d6bda6143e74db324a9/crates/zng-ext-hot-reload/src/lib.rs#L99).

We follow the same idea to propagate the tracing profiler context with the `LocalContext` to worker threads, clone the dispatcher and set it on the new context, except this time is in the dylib and set globally.

The same dispatcher sharing idea is used in the `tracing-shared` crate and it shows the same issue, see JakkuSakura/tracing-shared-rs#2.

**Comment by JakkuSakura** [comment]
Please refer to https://github.com/JakkuSakura/tracing-shared-rs/issues/2
basically it's to set a FakeSubscriber and convert it into Dispatch

**Comment by SamRodri** [comment]
Thanks for looking into this.
