### ISSUE TITLE
Bug in AutoGrowMode::rows() in Grid

### ISSUE THREAD

**Issue by mahdi739** [SamRodri/zng#238]
Hi in the zng-wgt-grid crate there is a function for `AutoGrowMode`  which I think is wrong:
```rust
    pub fn rows() -> Self {
        Self::Columns(u32::MAX)
    }
```
I guess it's supposed to be:
```rust
    pub fn rows() -> Self {
        Self::Rows(u32::MAX)
    }
```

**Comment by SamRodri** [comment]
Thanks for the report, you are definitely right that should be rows
