### ISSUE TITLE
`var` is not updated

### ISSUE THREAD

**Issue by mahdi739** [SamRodri/zng#378]
In this code I created a var which is passed to a Button and a TextInput, but it's not updated:
```rust
async fn main_window() -> WindowRoot {
  let counter = var(0);
  Window! {
    child = Stack!{
      direction=StackDirection::top_to_bottom();
      children=ui_vec![ 
        TextInput!{
          txt=counter.get_text();
        },
        Button!{
          child=Text!{txt=counter.get_text()};
          on_click=hn!(|_|{
            counter.modify(|f|*f.to_mut()+=1);
          });
        }
      ]
    }
  }
}
```
Sorry I wasn't sure it's a bug or I wrote something wrong.

**Comment by SamRodri** [comment]
`.get_text` gets the current var value converted to text, you need to use the var mapping functions to create a live binding. `TextInput` also has a helper property `txt_parse` that creates a bidi binding to a var.

```rust
async fn main_window() -> WindowRoot {
    let counter = var(0);
    Window! {
      child = Stack!{
        direction=StackDirection::top_to_bottom();
        children=ui_vec![ 
          TextInput! {
            txt_parse::<u32> = counter.clone();
          },
          Button! {
            child = Text!{ txt = counter.map_to_txt() };
            on_click = hn!(|_| {
                counter.modify(|f|*f.to_mut() += 1);
            });
          }
        ]
      }
    }
  }
```

**Comment by mahdi739** [comment]
Thank you. So basically `with` functions are not live binding (reactive?) but `map` functions are.

**Comment by SamRodri** [comment]
Yes  see the [`Var`](https://zng-ui.github.io/doc/zng/var/trait.Var.html) docs. The `with*` methods take in a closure that visits the current value without cloning, `get*`  methods get a clone of the current value, `map*` methods return a new var that updates when the source var updates, there are other methods that also return vars, if a method returns var that var is bound.

The `txt` property accepts `impl IntoVar<Txt>`,  values convert to read-only variables, already existing variable converts to themselves, thats how the same property can be static or live. So in your first code you set `txt` to a read-only text ("0").
